### ISSUE TITLE
Confusion caused by reportlab2

### ISSUE THREAD

**Issue by replabrobin** [talebi1/reportlab2#1]
By creating and promoting on pypi this version of reportlab you are causing confusion. I have just pushed reportlab 3.5.26 to pypi and now find that you have copied reportlab and created a version 3.5.26 and a version 3.5.27.

Would it not have been better to create a version without publishing and than ask for it to be incorporated?

**Comment by talebi1** [comment]
Apologies if the name (reportlab2) caused any confusion, we had no other solution than to release this to pypy because of an internal security policy restricting us from distributing 3rd party open source code to our clients. (Bumping the version number was not intentional, it was mandated by pypy for any minor change made to the package)

I have submitted this feature request (AES encryption) to the official reportlab project on bitbucket earlier this year
https://bitbucket.org/rptlab/reportlab/issues/167/add-support-for-aes-256-encyption

Unfortunately  no one looked into it, and the project seemed like it was not maintained anymore.

I don't like the idea of maintaining a separate fork just for a single feature,  so it would be great if someone could submit a pull request with support for AES encryption (I am not familiar with bitbucket or mercurial)  and I  will remove the package as soon as it is integrated in the official release.
